// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OprationResult struct {
	ActiveIp             string   `protobuf:"bytes,4,opt,name=activeIp,proto3" json:"activeIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OprationResult) Reset()         { *m = OprationResult{} }
func (m *OprationResult) String() string { return proto.CompactTextString(m) }
func (*OprationResult) ProtoMessage()    {}
func (*OprationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *OprationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OprationResult.Unmarshal(m, b)
}
func (m *OprationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OprationResult.Marshal(b, m, deterministic)
}
func (m *OprationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OprationResult.Merge(m, src)
}
func (m *OprationResult) XXX_Size() int {
	return xxx_messageInfo_OprationResult.Size(m)
}
func (m *OprationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OprationResult.DiscardUnknown(m)
}

var xxx_messageInfo_OprationResult proto.InternalMessageInfo

func (m *OprationResult) GetActiveIp() string {
	if m != nil {
		return m.ActiveIp
	}
	return ""
}

type Result struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MissCache            bool     `protobuf:"varint,2,opt,name=missCache,proto3" json:"missCache,omitempty"`
	ActiveIp             string   `protobuf:"bytes,4,opt,name=activeIp,proto3" json:"activeIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Result) GetMissCache() bool {
	if m != nil {
		return m.MissCache
	}
	return false
}

func (m *Result) GetActiveIp() string {
	if m != nil {
		return m.ActiveIp
	}
	return ""
}

func init() {
	proto.RegisterType((*Nil)(nil), "main.Nil")
	proto.RegisterType((*Key)(nil), "main.Key")
	proto.RegisterType((*KeyValue)(nil), "main.KeyValue")
	proto.RegisterType((*OprationResult)(nil), "main.OprationResult")
	proto.RegisterType((*Result)(nil), "main.Result")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x57, 0xb3, 0x8e, 0xf6, 0x32, 0x8a, 0x5c, 0x06, 0x96, 0xe2, 0xc3, 0xc8, 0x93, 0x88,
	0xf6, 0x61, 0xfe, 0x84, 0x3d, 0x88, 0x14, 0xa6, 0x54, 0x10, 0x5f, 0x63, 0xb9, 0x60, 0x30, 0x5b,
	0x4b, 0x92, 0x16, 0xf2, 0x1b, 0xfc, 0xd3, 0xd2, 0x44, 0xab, 0x22, 0xee, 0xed, 0x9e, 0x7b, 0x3e,
	0x4e, 0x72, 0x2e, 0x64, 0x86, 0xf4, 0x20, 0x1b, 0x32, 0x65, 0xa7, 0x5b, 0xdb, 0xe2, 0x7c, 0x2f,
	0xe4, 0x81, 0xc7, 0xc0, 0x76, 0x52, 0xf1, 0x33, 0x60, 0x15, 0x39, 0x3c, 0x05, 0xf6, 0x46, 0x2e,
	0x8f, 0xd6, 0xd1, 0x45, 0x5a, 0x8f, 0x23, 0xdf, 0x40, 0x52, 0x91, 0x7b, 0x12, 0xaa, 0xa7, 0xbf,
	0x2e, 0xae, 0x20, 0x1e, 0x46, 0x2b, 0x3f, 0xf1, 0xbb, 0x20, 0xf8, 0x15, 0x64, 0xf7, 0x9d, 0x16,
	0x56, 0xb6, 0x87, 0x9a, 0x4c, 0xaf, 0x2c, 0x16, 0x90, 0x88, 0xc6, 0xca, 0x81, 0xee, 0xba, 0x7c,
	0xee, 0xd1, 0x49, 0xf3, 0x67, 0x58, 0x7c, 0x52, 0x53, 0x5a, 0xf4, 0x23, 0x0d, 0xcf, 0x21, 0xdd,
	0x4b, 0x63, 0xb6, 0xa2, 0x79, 0x0d, 0xef, 0x24, 0xf5, 0xf7, 0xe2, 0x58, 0xf2, 0xe6, 0x3d, 0x82,
	0xa5, 0xa7, 0x1e, 0x43, 0x73, 0x5c, 0x03, 0xbb, 0x25, 0x8b, 0x69, 0x39, 0x56, 0x2f, 0x2b, 0x72,
	0xc5, 0x32, 0x8c, 0xe1, 0x03, 0x7c, 0x86, 0xd7, 0xc0, 0x1e, 0x7a, 0x8b, 0xd9, 0x44, 0xf8, 0xe6,
	0xc5, 0x2a, 0xe8, 0xdf, 0xad, 0xf8, 0x0c, 0x2f, 0x21, 0xde, 0x2a, 0x12, 0xfa, 0x2b, 0x72, 0x27,
	0xd5, 0x7f, 0xec, 0xcb, 0xc2, 0x9f, 0xfd, 0xe6, 0x23, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x20, 0xb6,
	0xef, 0x88, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheServiceClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
	Put(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*OprationResult, error)
	Clear(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*OprationResult, error)
}

type cacheServiceClient struct {
	cc *grpc.ClientConn
}

func NewCacheServiceClient(cc *grpc.ClientConn) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/main.CacheService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Put(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*OprationResult, error) {
	out := new(OprationResult)
	err := c.cc.Invoke(ctx, "/main.CacheService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Clear(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*OprationResult, error) {
	out := new(OprationResult)
	err := c.cc.Invoke(ctx, "/main.CacheService/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServiceServer is the server API for CacheService service.
type CacheServiceServer interface {
	Get(context.Context, *Key) (*Result, error)
	Put(context.Context, *KeyValue) (*OprationResult, error)
	Clear(context.Context, *Nil) (*OprationResult, error)
}

// UnimplementedCacheServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCacheServiceServer struct {
}

func (*UnimplementedCacheServiceServer) Get(ctx context.Context, req *Key) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCacheServiceServer) Put(ctx context.Context, req *KeyValue) (*OprationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedCacheServiceServer) Clear(ctx context.Context, req *Nil) (*OprationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clear not implemented")
}

func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&_CacheService_serviceDesc, srv)
}

func _CacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CacheService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CacheService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Put(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.CacheService/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Clear(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

var _CacheService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CacheService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _CacheService_Put_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _CacheService_Clear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
